WallRelatedPages::getMessagesRelatedArticleIds - one does not simply call wfGetDB() twice
Prevent PHP Notice: Object of class DatabaseMysqli could not be converted to int in /usr/wikia/slot1/13783/src/includes/db/LoadBalancer.php on line 491

followed by

Unexpected non-MediaWiki exception encountered, of type "Error"
Error: Call to a member function setLBInfo() on null in /usr/wikia/slot1/13783/src/includes/db/LoadBalancer.php:745