Fix fatal error in AbuseFilter extension
Fix the following error in AbuseFilter:
Fatal error: Cannot redeclare AbuseFilterHooks::onUserRenameLocal()

Fixed redeclaration of onUserRenameLocal which was meant to be
onUserRenameLocalIP.