Fix ForumTest and WikiaIFrameTagBuilderHelperTest
RuntimeException: failed to set return for WikiaIFrameTagBuilderHelper::isMobileSkin, the method is defined in WikiaTagBuilderHelper