ZipDirectoryReaderError: do not play dirty tricks with build-in PHP classes
Writing string to Exception::$code field was causing Apache segfaults after upgrading PHP to 5.6.11