Revert "Merge pull request #13580 from Wikia/SUS-1393"
This reverts commit d650274fb4889bdfe37dffec6651fe8dbd1d9990, reversing
changes made to d06480e7592b0e3fc6dd5c4439b72f654bc5cdf1.

Causes the following:

Unexpected non-MediaWiki exception encountered, of type "Error"
Error: Call to a member function getTempName() on null in /usr/wikia/slot1/19216/src/includes/upload/UploadBase.php:255
Stack trace:
0 /usr/wikia/slot1/19216/src/includes/upload/UploadFromUrl.php(202): UploadBase->verifyUpload()
1 /usr/wikia/slot1/19216/src/extensions/wikia/VideoHandlers/VideoFileUploader.class.php(334): UploadFromUrl->verifyUpload()
2 /usr/wikia/slot1/19216/src/extensions/wikia/VideoHandlers/VideoFileUploader.class.php(282): VideoFileUploader->uploadThumbnailFromUrl('https://i.ytimg...')
3 /usr/wikia/slot1/19216/src/extensions/wikia/VideoHandlers/VideoFileUploader.class.php(94): VideoFileUploader->uploadBestThumbnail('https://i.ytimg...')
4 /usr/wikia/slot1/19216/src/extensions/wikia/VideoEmbedTool/VideoEmbedTool_body.php(363): VideoFileUploader->upload(NULL)
5 /usr/wikia/slot1/19216/src/extensions/wikia/VideoEmbedTool/VideoEmbedTool_body.php(239): VideoEmbedTool->uploadVideoAsFile('youtube', 'iRvI4c9VsW8', 'Hamradun - Snep...', NULL)
6 /usr/wikia/slot1/19216/src/extensions/wikia/VideoEmbedTool/VideoEmbedTool_setup.php(98): VideoEmbedTool->insertFinalVideo()
7 /usr/wikia/slot1/19216/src/includes/AjaxDispatcher.php(118): VET()
8 /usr/wikia/slot1/19216/src/includes/Wiki.php(629): AjaxDispatcher->performAction()
9 /usr/wikia/slot1/19216/src/includes/Wiki.php(547): MediaWiki->main()
10 /usr/wikia/slot1/19216/src/index.php(58): MediaWiki->run()
11 {main}