Merge pull request #9996 from Wikia/PLATFORM-2027-prevent-segfaults-caused-by-ZipDirectoryReaderError
ZipDirectoryReaderError: do not play dirty tricks with build-in PHP classes