SUS-3471 | we no longer use MediaWiki-based jobs dispatcher
Avoid the following DB error on newly created wikis that do not have job table created anymore.

A database error has occurred.  Did you forget to run maintenance/update.php after upgrading?  See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: EXPLAIN SELECT  *  FROM `job`
Function: DatabaseMysqlBase::estimateRowCount
Error: 1146 Table 'tassomine.job' doesn't exist (geo-db-g-slave.query.consul)