wfGetDB: expect $db argument to be an integer
> wfGetDB(DB_SLAVE)
LoadBalancer::getReaderIndex: Using reader #1: slave.db-dev-db.service.consul...
Connecting to slave.db-dev-db.service.consul plpoznan...

> wfGetDB('foo')
Unexpected non-MediaWiki exception encountered, of type "TypeError"
TypeError: Argument 1 passed to wfGetDB() must be of the type integer, string given, called in maintenance/eval.php(88) : eval()'d code on line 1 and defined in includes/GlobalFunctions.php:3623